language: python

python:
- '2.7'

sudo: required

services:
- docker

notifications:
  email:
    recipients:
    - umaganapathyswork@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    secure: sIl5sn2pZV74hy8qYxlkMV6QgNLRx42Zq52nD8zWmLzHGIZI7hxTjr4UZeTtKHDLdpXTAbPjvmgQLD6ugfok7KBm/UwMTSdXZJPJD9Ats4IPfJyiWKgrwsjmUJE3XPVMyo+PmTalRgiYwoG4CGcscaHVmAByOXFMhHyK/B6pFoJ26ohMeDXJ+Vm4iozeyfZbhEYH6kBa+LshTqolUayOBhM1nw+MErQ+DVy0xnHV4khlU/Mqay6shwcz9hXBqaFJ5/KErsFI/NGQAprTsfyQKKufnH425dx+IiOO2Gpt2Ox2GCSZS99cPYjxsNQvWHCFD9dYICamDqLkViM1OjqNrgdzC9C5SKM4eqfFko43/SNvqvz39wOhed+PUPTe7HB1SlUohjMWP2tlcF5//jZlK9njVL16TYBdAABHPhnv5Ki+seKM3I2EimntlJRdA6Yx20WTW7IcHhb03YMhlJRdyaHenHn++e6gWC+PZ+oKCvOE3d7t/eQDegjDTsHbDBe1oJ0hrvi0yJKQf5GEEG24+4/LgwdNziUTMO/1r7LVY8KqE1oYcGyMgtrPn9R7Cyb+i+0Nz4xs06p8hP1vpbbT4SL2Z38nSjrNUvk0rXDU9qVJCXcovVYfqjiEUgdbDdG/pg+bPij3u4lN5gXw12dloXuj5PWzLSF+amL1AzYGHuU=

branches:
  only:
  - master

before_install:
- docker version
- python --version
- javac -version
- java -version

install:
- pip install coveralls
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH
- cd ../
- git clone https://github.com/ugswork/ExpressionAPI.git
- cd ExpressionAPI
- kb-sdk test || true
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
  test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
- pwd=$(pwd)
- echo "#!/bin/bash" >> test_local/run_subjob.sh
- echo -e "$pwd/test_local/run_docker.sh run --rm --user 0:0 -v $pwd/test_local/subjobs/\$1/workdir:/kb/module/work
  -v $pwd/test_local/workdir/tmp:/kb/module/work/tmp \$4 -e \"SDK_CALLBACK_URL=\$3\"
  \$2 async" >> test_local/run_subjob.sh
- cat test_local/run_subjob.sh

script:
- kb-sdk test

after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/ExpressionAPI /kb/module/lib/
- pwd
- ls -l /kb/module/lib/ExpressionAPI
- cat .coverage
- coverage report -m
- coveralls
